### ISSUE TITLE
soy beans 无获取途径，与wiki描述不符

### ISSUE THREAD

**Issue by usrcao** [OwnBugTracker/isMineCraft#10]
**描述 Bug**：
![image](https://github.com/user-attachments/assets/401d18db-11fd-4bc7-b27a-0e6a1c7f6e97)
![image](https://github.com/user-attachments/assets/bf7c1c22-712b-4c3c-82f3-928eb835f937)

**涉及模组**：
doggy talents next
**复现步骤**：
玩你服沙了几百只僵尸都没爆过

**预期行为**：
击杀僵尸概率掉落soy beans

**Comment by SanQianQVQ** [comment]
该问题可能属于模组问题，预期通过 Lootjs 为僵尸添加掉落物来间接修复

**Comment by SanQianQVQ** [comment]
已通过 LootJS 为僵尸添加该掉落物，概率10%

**Comment by SanQianQVQ** [comment]
![image](https://github.com/user-attachments/assets/7ffbffea-69e0-47ef-a877-c33f1ed4faa8)
