### ISSUE TITLE
[Bug] 镇压之杖无法阻止幻翼生成

### ISSUE THREAD

**Issue by usrcao** [OwnBugTracker/isMineCraft#12]
**描述 Bug**：
放置镇压之杖后幻翼照常生成
![image](https://github.com/user-attachments/assets/4c9da711-45e7-4c63-a974-2aad0ffbf515)

**涉及模组**：
Bosses of mass destruction

**预期行为**：
放置后，周围64格将不再生成怪物

**Comment by SanQianQVQ** [comment]
该问题属于模组问题，建议前往 https://github.com/barribob/bosses-of-mass-destruction/issues 提出
