### ISSUE TITLE
樱桃果味红葡萄酒 搅拌机配方丢失

### ISSUE THREAD

**Issue by usrcao** [OwnBugTracker/isMineCraft#8]
**描述 Bug**：
![image](https://github.com/user-attachments/assets/e56466fa-d938-4c4f-8266-2cc90936981c)
![image](https://github.com/user-attachments/assets/9d618245-2d1e-4fd1-9248-102cb5ea9bd8)
对应搅拌配方结果为空

**涉及模组**：
create，[let's ]do]vinery
**复现步骤**：
将配方所需材料放入工作盆中搅拌

**预期行为**：
获得樱桃果味红葡萄酒

**Comment by SanQianQVQ** [comment]
这是一个错误的配方兼容问题，实际上不能也不应使用机械动力进行酿酒，应该是兼容层默认扫描了配方导致的
该问题不会修复，或者考虑移除此类自动兼容化的配方
