### ISSUE TITLE
Heartburger配方缺失

### ISSUE THREAD

**Issue by usrcao** [OwnBugTracker/isMineCraft#9]
**描述 Bug**：
配方中存在空白项，无法合成

**涉及模组**：
silents delight

**截图**：
![image](https://github.com/user-attachments/assets/853ee73a-ad6e-44aa-b94e-860dcdca2b90)
![image](https://github.com/user-attachments/assets/c351b6aa-f437-49eb-93a8-c9082fb585b1)

**Comment by SanQianQVQ** [comment]
![image](https://github.com/user-attachments/assets/7304f760-98cd-465d-88c2-3a569956a56c)
配方已修正，请在游戏内查看
